# LambdaTest Configuration

# Project and folder configuration
project_id: "01KMN0F6H6RJEHK7KVZB3GW6W5"
folder_id: "01KMN0F6JVZPFWT3MDVZ8VQ5D5"

# Test Run configuration
assignee: 3126589
environment_id: 282683

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"